<!DOCTYPE html>
<html>
<head>
    <title>Billing Software</title>
    <style>
        /* CSS styles for the bill */
        .bill {
            border: 1px solid #ccc;
            padding: 20px;
            width: 300px;
            margin: 0 auto;
        }

        .bill h2 {
            text-align: center;
        }

        .bill p {
            margin: 5px 0;
        }
    </style>
</head>
<body>
    <form>
        <label for="customer-name">Customer Name:</label>
        <input type="text" id="customer-name"><br><br>

        <label for="item-name">Item Name:</label>
        <input type="text" id="item-name"><br><br>

        <label for="quantity">Quantity:</label>
        <input type="number" id="quantity"><br><br>

        <label for="price">Price:</label>
        <input type="number" id="price"><br><br>

        <button type="button" onclick="generateBill()">Generate Bill</button>
    </form>

    <div id="bill-container"></div>

    <script>
        function generateBill() {
            // Get input values
            var customerName = document.getElementById("customer-name").value;
            var itemName = document.getElementById("item-name").value;
            var quantity = document.getElementById("quantity").value;
            var price = document.getElementById("price").value;

            // Calculate total amount
            var totalAmount = quantity * price;

            // Generate bill HTML
            var billHTML = '<div class="bill">';
            billHTML += '<h2>Bill</<!DOCTYPE html>
